services:
  bla-web-api:
    build: ./
    container_name: bla-web-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost:5432
      DB_NAME: bla_user_db
    ports:
      - "8080:8080"
    networks: 
      - app-network
    depends_on: 
      - db_postgres
  
  db_postgres:
    image: postgres:16.3
    restart: always 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bla_user_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
networks:
  app-network: